apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-hoge/deployment.yaml
- service-hoge/service.yaml
- service-fuga/deployment.yaml
- service-fuga/service.yaml
- nginx/deployment.yaml
- nginx/service.yaml

configMapGenerator:
- files:
  - nginx/nginx-config/default.conf
  name: nginx-config
- files:
  - nginx/envoy-config/envoy.yaml
  name: envoy-config
