apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hoge
spec:
  maxReplicas: 30
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-hoge
  targetCPUUtilizationPercentage: 100
