apiVersion: v1
kind: Service
metadata:
  annotations:
  name: service-hoge
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: service-hoge
  type: ClusterIP
  clusterIP: None
