apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.17.9
        name: nginx
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      - image: envoyproxy/envoy:v1.13.1
        name: envoy
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: envoy-config
          configMap:
            name: envoy-config
