apiVersion: v1
kind: Service
metadata:
  annotations:
  name: service-fuga
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: service-fuga
  type: ClusterIP
  clusterIP: None
